// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhSZpls71cteMoMA2sKdUgqGxVt3cXrA',
    appId: '1:46991235039:web:5939eb9d6632718cca166a',
    messagingSenderId: '46991235039',
    projectId: 'pmds-project',
    authDomain: 'pmds-project.firebaseapp.com',
    storageBucket: 'pmds-project.firebasestorage.app',
    measurementId: 'G-ZNVWQD5MM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGUM4yx_UjiGP_cAD1hxCFf5mNSnMCqI',
    appId: '1:46991235039:android:00ecca57c9cd4e07ca166a',
    messagingSenderId: '46991235039',
    projectId: 'pmds-project',
    storageBucket: 'pmds-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIR8TGftRme8eMwQyAX_acvFf-FpnLqDE',
    appId: '1:46991235039:ios:a175f8e0d8ebb906ca166a',
    messagingSenderId: '46991235039',
    projectId: 'pmds-project',
    storageBucket: 'pmds-project.firebasestorage.app',
    iosBundleId: 'com.example.cadMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIR8TGftRme8eMwQyAX_acvFf-FpnLqDE',
    appId: '1:46991235039:ios:a175f8e0d8ebb906ca166a',
    messagingSenderId: '46991235039',
    projectId: 'pmds-project',
    storageBucket: 'pmds-project.firebasestorage.app',
    iosBundleId: 'com.example.cadMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzhSZpls71cteMoMA2sKdUgqGxVt3cXrA',
    appId: '1:46991235039:web:1a281a0be2c81b2dca166a',
    messagingSenderId: '46991235039',
    projectId: 'pmds-project',
    authDomain: 'pmds-project.firebaseapp.com',
    storageBucket: 'pmds-project.firebasestorage.app',
    measurementId: 'G-LCKB6GFWZB',
  );
}
